name: Create CSV File

on:
  workflow_dispatch:

jobs:
  generate-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate CSV file
        run: |
          echo "id,value" > random_values.csv
          for i in {1..10}; do
            echo "$i,$((RANDOM % 100))" >> random_values.csv
          done

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v3
        with:
          name: random-values
          path: random_values.csv
