name: Consume CSV File

on:
  workflow_run:
    workflows:
      - Create CSV File
    types:
      - completed

jobs:
  consume-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Download CSV artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: random-values
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: 12991355666

      - name: Print CSV contents
        run: |
          echo "CSV contents:"
          cat random_values.csv
